apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30030   # Adding NodePort configuration
  selector:
    app: guestbook-ui
  type: NodePort     
